name: ci_cd test

on:
  push:
    branches:
      - "main"
# гит ветка при комите в которую происходит запуск ci/cd

jobs:
  build:
    runs-on: ubuntu-latest
#определяет опреационную систему docker образов в которых будут выполняться шаги steps
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
  # проверка github репозитория на наличие папки .github/workflows и файла .yml с инструкциями ci/cd
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    #проверка пользователя для выгрузки образа в dockerhub
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    #установка сборщика образов docker из файла Dockerfile
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nginxtest:latest
      #сборка образа докер и выгрузка его в docker hub
      -
        name: telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: FIX BUG!
      #оповещение о выполнении в ТГ
