name: ci_cd test

on:
  push:
    branches:
      - "main"
#a git branch, where ci/cd pipeline launches after committing 

jobs:
  build:
    runs-on: ubuntu-latest
#defines the operating system of the docker images in which the steps will be executed
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
  #checking github repository for .github/workflows folder and .yml file with ci/cd instructions
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    #checking the user to upload the image to dockerhub, the password and login are not safe to specify, so we use secrets
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    #installing the docker image builder from a Dockerfile
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nginxtest:latest
      #building a docker image and uploading it to docker hub
      -
        name: telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: FIX BUG!
      #execution notification in TG
      - 
        name: Deploy to Docker
        uses: wshihadeh/docker-deployment-action@v1
        with:
           remote_docker_host: examplehost ip or name
           #deployment computer address
           ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
           ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
           #authorization keys on a remote computer
           deployment_mode: docker
           #deployment mode
           args: nginx:latest
           #name of the container on the virtual machine
